
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://erfbmgcxpmtnmkffqsac.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVyZmJtZ2N4cG10bm1rZmZxc2FjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0Njg4MDksImV4cCI6MjA2NjA0NDgwOX0.PWwKx_XIBMrELZJhVg96PwgnNRT6xnoAjOftyYR4g54";

// Create the supabase client with enhanced configuration
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true
  },
  global: {
    headers: {
      'x-client-info': 'supabase-js-web/2.50.0'
    }
  },
  db: {
    schema: 'public'
  },
  realtime: {
    params: {
      eventsPerSecond: 10
    }
  }
});

// Health check function to verify Supabase connection
export const healthCheck = async (): Promise<boolean> => {
  try {
    const { error } = await supabase.from('projects').select('count', { count: 'exact', head: true });
    return !error;
  } catch {
    return false;
  }
};

// Network connectivity check
export const checkNetworkConnectivity = (): boolean => {
  return navigator.onLine;
};
